[package]
name = "parser-gen"
version = "0.2.2"
authors = ["Edouard Oger <eoger@fastmail.com>"]
edition = "2018"
license = "MPL-2.0"
publish = false

[dependencies]
lalrpop = { version = "0.19", features = ["lexer"] }
